### ISSUE TITLE
Tracking dfe-frontend-alpha dependency

### ISSUE THREAD

**Issue by RogerHowellDfE** [DFE-Digital/service-assessment-service#119]
DfE Frontend dependency updated version recently via Dependabot / #111 

- The updated dfe-frontend-alpha dependency appears to break the build 
  - [x] Temporary revert of this via #116 until build issues are resolved
- This project did not have PR checks in place to catch this prior to merging
  - [x] PR checks are now added via #117 and #118 
  - [x] Build and test is now configured as a required PR check, which should prevent any future accidental build-breaking updates/changes
- Additional investigations
  - [ ] Upstream link: https://github.com/DFE-Digital/dfe-frontend/issues/2
  - [ ] Update once investigations completed and version upgrade possible

**Comment by RogerHowellDfE** [comment]
Appears to be building fine in v1.0.1 (#147) -- closing 👍
